baseURL = 'https://solmazfs.github.io/blog'
canonifyURLs = true
languageCode = 'en-us'
copyright = '© 2021-2022'
title = 'blog.solmazfs'
enableEmoji = true
enableGitInfo = true

[author]
    name = 'solmazfs'

[menu]

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    identifier = "mixed-log"
    name = "Mixed-Log"
    url = "/mixedlog/"
    weight = 4

  [[menu.main]]
    identifier = "now"
    name = "Now"
    url = "/now/"
    weight = 5


[taxonomies]
    category = 'categories'
    tag = 'tags'

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
            hardWraps = false

    [markup.highlight]
        codeFences = true
        guessSyntax = true
        hl_Lines = ""
        lineNoStart = 1
        tabWidth = 4
        noClasses = false

[frontmatter]
    lastmod = [ "lastmod", ":git", "date", "publishDate" ]
