baseURL = 'https://solmazfs.github.io/blog/'
languageCode = 'en-us'
title = 'blog'
theme = "tm-academic"

[menu]
	[[menu.main]]
		name = "posts"
		url = "/posts/"
		weight = 10
	[[menu.main]]
		name = "categories"
		url = "/categories/"
		weight = 20
	[[menu.main]]
		name = "projects"
		url = "/projects/"
		weight = 30
	[[menu.main]]
		name = "now"
		url = "/now/"
		weight = 40
	[[menu.main]]
		name = "log"
		url = "/log/"
		weight = 50

[params]
    copyright = "BY-NC-SA 4.0"
    author = "solmazfs"
